Fixed potential cyclic reference in cargo.
zebp/worker-kv pull request #9
Opened 2022-09-22 07:25 UTC by CMoore-Darwinium

This changes worker to use serde-wasm-bindgen package, rather than relying on the deprecated serde option in wasm-bindgen.

See:
https://docs.rs/serde-wasm-bindgen/latest/serde_wasm_bindgen/

See the following issues:
https://github.com/tkaitchuck/aHash/issues/95
https://github.com/rustwasm/wasm-bindgen/issues/1258

Removed the usage of wasm_bindgen::JsValue::from_serde and wasm_bindgen::JsValue::into_serde that have been deprecated.

Added the new serde_wasm_bindgen::from_value() and serde_wasm_bindgen::to_value() equivalents instead.

2022-09-23 00:13 UTC, zebp requested changes
I'm apprehensive to use `serde-wasm-bindgen`, which would add another error variant and expand what can and can't be deserialized, both of which I'm a bit uncomfortable with. As noted in the documentation of [JsValue::from_serde](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/struct.JsValue.html#method.from_serde), `gloo-utils`' [JsValueSerdeExt](https://docs.rs/gloo-utils/latest/gloo_utils/format/trait.JsValueSerdeExt.html) has serde-based json serialization while using `serde_json`'s error type and is still strictly JSON-able types. I think this PR should switch to `gloo-utils` to solve the dependency cycle.

2022-09-23 00:20 UTC, CMoore-Darwinium commented
serde-wasm-bindgen in theory will allow a superset of what gloo-utils can serialize, as well as leading to a smaller binary size.
serde-wasm-bindgen's error is just a wrapper around JsValue, we can change it to the KvError::JavaScript variant to maintain the same number of varients.

2022-09-23 13:37 UTC, zebp commented
> serde-wasm-bindgen in theory will allow a superset of what gloo-utils can serialize

I'm aware, but I'd prefer if we kept the set of items that could be serialized the same as what we have currently.


> serde-wasm-bindgen's error is just a wrapper around JsValue, we can change it to the KvError::JavaScript variant to maintain the same number of varients.

This would break anyone's code that was relying on getting a serialization error if the input could not be serialized, which I'd don't want to do.


Also as for binary size, I don't think it'll make much of a difference as anything unrelated to serialization will get removed when linking as it's unused when we use the extension trait.

2022-09-27 03:56 UTC, CMoore-Darwinium commented
There is now a gloo_utils based pull request.

2022-09-27 04:23 UTC, closed without merging